# Generated by Django 3.2.9 on 2021-12-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='receipt',
        ),
        migrations.AddField(
            model_name='receipt',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wydatki.product'),
        ),
    ]
