# Generated by Django 3.2.9 on 2022-01-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wydatki.receipt'),
        ),
    ]
