# Generated by Django 3.2.9 on 2022-02-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wydatki', '0002_auto_20220123_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wydatki.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='wydatki.shop'),
            preserve_default=False,
        ),
    ]
